"""Supplier Budget table

Revision ID: b1024d92877f
Revises: 93875bdac5a3
Create Date: 2025-08-01 15:07:35.648312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1024d92877f'
down_revision: Union[str, Sequence[str], None] = '93875bdac5a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SUPPLIER_BUDGET',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('VENDOR_ID', sa.String(length=15), nullable=True),
    sa.Column('DESCR', sa.String(length=120), nullable=True),
    sa.Column('FISCAL_YEAR', sa.String(length=4), nullable=True),
    sa.Column('FUND_CODE', sa.String(length=4), nullable=True),
    sa.Column('PROGRAM_CODE', sa.String(length=4), nullable=True),
    sa.Column('ACCOUNT', sa.String(length=10), nullable=True),
    sa.Column('OPERATING_UNIT', sa.String(length=4), nullable=True),
    sa.Column('DEPTID', sa.String(length=10), nullable=True),
    sa.Column('PROJECT_ID', sa.String(length=26), nullable=True),
    sa.Column('BUSINESS_UNIT', sa.String(length=5), nullable=True),
    sa.Column('AMOUNT', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SUPPLIER_BUDGET')
    # ### end Alembic commands ###
